# Generated by Django 4.1 on 2022-09-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0034_cartacelular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_vehiculo', models.CharField(max_length=10)),
                ('marca_vehiculo', models.CharField(max_length=20)),
                ('modelo_vehiculo', models.CharField(max_length=40)),
                ('numero_serie_vehiculo', models.CharField(max_length=50)),
                ('color_vehiculo', models.CharField(max_length=20)),
                ('año_vehiculo', models.CharField(max_length=4)),
                ('placa_vehiculo', models.CharField(max_length=15)),
                ('transmision_vehiculo', models.CharField(max_length=12)),
                ('ultimo_km_registrado', models.IntegerField()),
                ('status_vehiculo', models.CharField(max_length=20)),
                ('motivo_status_vehiculo', models.CharField(max_length=255, null=True)),
                ('fecha_alta_vehiculo', models.DateField()),
                ('imagen_frontal_vehiculo', models.ImageField(null=True, upload_to='vehiculos')),
                ('imagen_trasera_vehiculo', models.ImageField(null=True, upload_to='vehiculos')),
                ('imagen_lateralIzquierda_vehiculo', models.ImageField(null=True, upload_to='vehiculos')),
                ('imagen_lateralDerecha_vehiculo', models.ImageField(null=True, upload_to='vehiculos')),
                ('responsable_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='tenenciasVehiculos',
            fields=[
                ('id_tenencia', models.AutoField(primary_key=True, serialize=False)),
                ('recibio_tenencia_vehiculo', models.FileField(upload_to='tenenciasvehiculo')),
                ('fecha_tenencia', models.DateField()),
                ('placas_nuevas', models.CharField(max_length=2)),
                ('referencia_pago_tenencia', models.CharField(max_length=20)),
                ('monto_pagado_vehiculo', models.FloatField(max_length=30)),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='serviciosVehiculos',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_servicios_vehiculo', models.DateField()),
                ('tipo_servicio', models.CharField(max_length=20)),
                ('servicios_realizados', models.CharField(max_length=255)),
                ('kilometraje_preservicio', models.IntegerField()),
                ('taller_servicio', models.CharField(max_length=50)),
                ('monto_pagado', models.CharField(max_length=20)),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='documentacionVehiculos',
            fields=[
                ('id_documentacion', models.AutoField(primary_key=True, serialize=False)),
                ('factura_vehiculo', models.FileField(null=True, upload_to='facturasvehiculos')),
                ('tarjeta_circulacion', models.FileField(null=True, upload_to='facturasvehiculos')),
                ('pago_seguro', models.FileField(null=True, upload_to='facturasvehiculos')),
                ('contrato_arrendamiento', models.FileField(null=True, upload_to='facturasvehiculos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='alineacionyBalanceo',
            fields=[
                ('id_alineacion_balanceo', models.AutoField(primary_key=True, serialize=False)),
                ('alineacion_realizada', models.CharField(max_length=2)),
                ('balanceo_realizado', models.CharField(max_length=2)),
                ('cambio_llantas', models.CharField(max_length=255)),
                ('numero_cambio_llantas', models.IntegerField()),
                ('medida_llanta_nueva', models.IntegerField()),
                ('marca_llanta_nueva', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('kilometraje_prealineacion', models.IntegerField()),
                ('fecha_alineacion', models.DateField()),
                ('factura_alineacion', models.FileField(null=True, upload_to='facturasalineacion')),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
    ]
