# Generated by Django 4.0.4 on 2022-10-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0035_vehiculos_tenenciasvehiculos_serviciosvehiculos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenenciasvehiculos',
            name='ano_pagado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentacionvehiculos',
            name='contrato_arrendamiento',
            field=models.FileField(null=True, upload_to='contratosArrendamientosVehiculos'),
        ),
        migrations.AlterField(
            model_name='documentacionvehiculos',
            name='factura_vehiculo',
            field=models.FileField(null=True, upload_to='facturasVehiculos'),
        ),
        migrations.AlterField(
            model_name='documentacionvehiculos',
            name='pago_seguro',
            field=models.FileField(null=True, upload_to='segurosVehiculos'),
        ),
        migrations.AlterField(
            model_name='documentacionvehiculos',
            name='tarjeta_circulacion',
            field=models.FileField(null=True, upload_to='tarjetasCirculacionVehiculos'),
        ),
    ]
