# Generated by Django 4.0.4 on 2022-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0037_reparacionvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacionybalanceo',
            name='medida_llanta_nueva',
            field=models.CharField(max_length=255),
        ),
    ]
