# Generated by Django 4.0.4 on 2022-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0038_alter_alineacionybalanceo_medida_llanta_nueva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacionybalanceo',
            name='marca_llanta_nueva',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alineacionybalanceo',
            name='medida_llanta_nueva',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alineacionybalanceo',
            name='numero_cambio_llantas',
            field=models.IntegerField(null=True),
        ),
    ]
