# Generated by Django 4.0.4 on 2022-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0039_alter_alineacionybalanceo_marca_llanta_nueva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosvehiculos',
            name='factura_servicios',
            field=models.FileField(null=True, upload_to='facturasServiciosVehiculos'),
        ),
    ]
