# Generated by Django 4.0.4 on 2022-11-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0040_serviciosvehiculos_factura_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacionybalanceo',
            name='monto_pagado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
