# Generated by Django 4.0.4 on 2022-11-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0041_alineacionybalanceo_monto_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='cambiosVehiculares',
            fields=[
                ('id_cambio_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateField()),
                ('kilometraje_camibo', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('daños', models.CharField(max_length=255, null=True)),
                ('firma_encargado_anterior', models.ImageField(null=True, upload_to='firmaCambioVehiculoAnterior')),
                ('firma_encargado_nuevo', models.ImageField(null=True, upload_to='firmaCambioVehiculoNuevo')),
                ('encargado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='asignacionesVehiculares',
            fields=[
                ('id_asignacion_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('kilometraje_asignacion', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('daños', models.CharField(max_length=255, null=True)),
                ('firma_encargado_asignado', models.ImageField(null=True, upload_to='firmaAsignacionVehiculos')),
                ('firma_empleado_agregadopor', models.ImageField(null=True, upload_to='firmaEmpleadoAgregadoPorAsignacion')),
                ('encargado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.vehiculos')),
            ],
        ),
    ]
