# Generated by Django 4.0.4 on 2022-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0042_cambiosvehiculares_asignacionesvehiculares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionesvehiculares',
            name='encargado_asignado',
        ),
        migrations.RemoveField(
            model_name='cambiosvehiculares',
            name='encargado_anterior',
        ),
        migrations.AddField(
            model_name='asignacionesvehiculares',
            name='encargado_asignado_y_agregadopor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cambiosvehiculares',
            name='encargado_anterior_y_nuevo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
