# Generated by Django 4.0.4 on 2022-12-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0044_cambiosvehiculares_agregado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionesDesempeno',
            fields=[
                ('id_evaluacion_desempeno', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_evaluacion', models.CharField(max_length=10)),
                ('nombre_evaluacion', models.CharField(max_length=40)),
                ('estatus_general', models.CharField(max_length=15)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorEvaluador',
            fields=[
                ('id_indicador_evaluador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('estatus_general', models.CharField(max_length=20)),
                ('empleados_evaluados', models.CharField(max_length=20)),
                ('estatus_empleados_evaluador', models.CharField(max_length=20)),
                ('agregado_por', models.CharField(max_length=3)),
                ('empleado_evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('evaluacion_desempeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.evaluacionesdesempeno')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosDesempeno',
            fields=[
                ('id_resultado_desempeno', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_preguntas', models.CharField(max_length=255)),
                ('estatus_resultado_preguntas', models.CharField(max_length=255)),
                ('fecha_terminacion', models.DateField(null=True)),
                ('estatus_resultado', models.CharField(max_length=20)),
                ('id_empleado_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('indicador_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.indicadorevaluador')),
            ],
        ),
    ]
