# Generated by Django 4.0.4 on 2022-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0045_evaluacionesdesempeno_indicadorevaluador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesdesempeno',
            name='estatus_evaluadores',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
