# Generated by Django 4.0.4 on 2023-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0046_evaluacionesdesempeno_estatus_evaluadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadorevaluador',
            name='empleados_evaluados',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultadosdesempeno',
            name='estatus_resultado',
            field=models.CharField(max_length=50),
        ),
    ]
