# Generated by Django 4.0.4 on 2023-02-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0048_alter_indicadorevaluador_estatus_empleados_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadosCara',
            fields=[
                ('id_empleado_cara', models.AutoField(primary_key=True, serialize=False)),
                ('cara_registrada', models.CharField(max_length=2)),
                ('cara_activa', models.CharField(max_length=2)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
