# Generated by Django 4.0.4 on 2023-02-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0049_empleadoscara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_entrada', models.CharField(max_length=8)),
                ('retardo', models.CharField(max_length=2)),
                ('hora_salida', models.CharField(max_length=8)),
                ('a_tiempo', models.CharField(max_length=2)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
