# Generated by Django 4.0.4 on 2023-02-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0050_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='a_tiempo',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='retardo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
