# Generated by Django 4.0.4 on 2023-02-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0051_asistencia_fecha_alter_asistencia_a_tiempo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosAsistencia',
            fields=[
                ('id_permiso_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaSalidaTemprana',
            fields=[
                ('id_incidencia_salida_temprana', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora_salida', models.CharField(max_length=8, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_asitencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaSalidaFuera',
            fields=[
                ('id_incidencia_salida_fuera', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora_salida', models.CharField(max_length=8, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_asitencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaLlegadaTardia',
            fields=[
                ('id_incidencia_llegada_tardia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora_entrada', models.CharField(max_length=8, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_asitencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id_horas_extras', models.AutoField(primary_key=True, serialize=False)),
                ('numero_horas_extras', models.IntegerField()),
                ('id_asitencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.asistencia')),
            ],
        ),
    ]
