# Generated by Django 4.0.4 on 2023-02-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0052_permisosasistencia_incidenciasalidatemprana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltasAsistencia',
            fields=[
                ('id_falta_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('observaciones', models.CharField(max_length=255)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
