# Generated by Django 4.0.4 on 2023-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0054_asistenciaproyectoforaneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaproyectoforaneo',
            name='salida_siguiente_dia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciaproyectoforaneo',
            name='proyecto_interno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
