# Generated by Django 4.0.4 on 2023-02-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0055_asistenciaproyectoforaneo_salida_siguiente_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasExtrasForaneas',
            fields=[
                ('id_horas_extras_foraneas', models.AutoField(primary_key=True, serialize=False)),
                ('numero_horas_extras', models.IntegerField()),
                ('id_asitencia_foraneas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.asistenciaproyectoforaneo')),
            ],
        ),
    ]
