# Generated by Django 4.0.4 on 2023-03-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0056_horasextrasforaneas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionNFCEmpleado',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('uid_nfc', models.IntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
