# Generated by Django 4.0.4 on 2023-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0057_relacionnfcempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionnfcempleado',
            name='uid_nfc',
            field=models.CharField(max_length=255),
        ),
    ]
