# Generated by Django 4.1.7 on 2023-03-24 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0059_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaproyectoforaneo',
            name='proyecto_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.proyectos'),
        ),
    ]
