# Generated by Django 4.1.7 on 2023-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0060_alter_asistenciaproyectoforaneo_proyecto_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaproyectoforaneo',
            name='actividades_realizadas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaproyectoforaneo',
            name='motivo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
