# Generated by Django 4.1.7 on 2023-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0061_asistenciaproyectoforaneo_actividades_realizadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaproyectoforaneo',
            name='personal_externo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
